# Famous Instagram accounts (followers in millions, approx. as of Dec 2025)
data = [
    {"name": "Instagram", "followers": 697, "description": "Official Instagram platform account"},
    {"name": "Cristiano Ronaldo", "followers": 668, "description": "Portuguese footballer"},
    {"name": "Lionel Messi", "followers": 510, "description": "Argentinian footballer"},
    {"name": "Selena Gomez", "followers": 416, "description": "American singer and actress"},
    {"name": "Kylie Jenner", "followers": 391, "description": "American media personality and businesswoman"},
    {"name": "Dwayne Johnson", "followers": 391, "description": "American actor and former professional wrestler"},
    {"name": "Ariana Grande", "followers": 373, "description": "American singer and actress"},
    {"name": "Kim Kardashian", "followers": 354, "description": "American media personality and businesswoman"},
    {"name": "Beyoncé", "followers": 308, "description": "American singer and actress"},
    {"name": "Khloé Kardashian", "followers": 300, "description": "American media personality"},
    {"name": "Nike", "followers": 298, "description": "Global sportswear brand"},
    {"name": "Justin Bieber", "followers": 292, "description": "Canadian singer"},
    {"name": "Kendall Jenner", "followers": 285, "description": "American model and TV personality"},
    {"name": "Taylor Swift", "followers": 281, "description": "American singer and songwriter"},
    {"name": "National Geographic", "followers": 276, "description": "Magazine and media brand about science and nature"},
    {"name": "Virat Kohli", "followers": 274, "description": "Indian cricketer"},
    {"name": "Jennifer Lopez", "followers": 247, "description": "American singer and actress"},
    {"name": "Neymar", "followers": 231, "description": "Brazilian footballer"},
    {"name": "Kourtney Kardashian", "followers": 216, "description": "American media personality"},
    {"name": "Miley Cyrus", "followers": 211, "description": "American singer and actress"},
    {"name": "Katy Perry", "followers": 202, "description": "American singer"},
    {"name": "Real Madrid CF", "followers": 180, "description": "Spanish professional football club"},
    {"name": "Zendaya", "followers": 176, "description": "American actress and singer"},
    {"name": "Kevin Hart", "followers": 176, "description": "American comedian and actor"},
    {"name": "Cardi B", "followers": 163, "description": "American rapper"},
    {"name": "LeBron James", "followers": 158, "description": "American basketball player"},
    {"name": "Demi Lovato", "followers": 152, "description": "American singer and actress"},
    {"name": "Rihanna", "followers": 149, "description": "Barbadian singer and businesswoman"},
    {"name": "FC Barcelona", "followers": 145, "description": "Spanish professional football club"},
    {"name": "Chris Brown", "followers": 144, "description": "American singer"},
    {"name": "Drake", "followers": 142, "description": "Canadian rapper and singer"},
    {"name": "Ellen DeGeneres", "followers": 134, "description": "American comedian and TV host"},
    {"name": "Kylian Mbappé", "followers": 128, "description": "French footballer"},
    {"name": "Billie Eilish", "followers": 124, "description": "American singer and songwriter"},
    {"name": "UEFA Champions League", "followers": 121, "description": "European club football competition"},
    {"name": "Lisa", "followers": 106, "description": "Thai rapper and singer, member of Blackpink"},
    {"name": "Gal Gadot", "followers": 106, "description": "Israeli actress"},
    {"name": "Vin Diesel", "followers": 104, "description": "American actor"},
    {"name": "Narendra Modi", "followers": 99, "description": "Prime Minister of India"},
    {"name": "NASA", "followers": 97, "description": "United States space agency"},
    {"name": "Shraddha Kapoor", "followers": 95, "description": "Indian actress"},
    {"name": "Shakira", "followers": 94, "description": "Colombian singer"},
    {"name": "Priyanka Chopra", "followers": 94, "description": "Indian actress"},
    {"name": "NBA", "followers": 90, "description": "North American professional basketball league"},
    {"name": "Dua Lipa", "followers": 89, "description": "British singer and songwriter"},
    {"name": "Snoop Dogg", "followers": 89, "description": "American rapper"},
    {"name": "Jennie", "followers": 89, "description": "South Korean singer, member of Blackpink"},
    {"name": "David Beckham", "followers": 88, "description": "English former footballer"},
    {"name": "Alia Bhatt", "followers": 87, "description": "Indian actress"},
    {"name": "Rosé", "followers": 84, "description": "New Zealand–born singer, member of Blackpink"},
]